# Generated by Django 4.1.2 on 2022-12-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_cart_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderby',
            name='total',
            field=models.IntegerField(default=1),
        ),
    ]
